import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./common/Navbar";
import Footer from "./common/Footer";
import { ToastProvider } from "./Toast/ToastContext";
import { NotificationSocketProvider } from "./context/NotificationSocketContext";
import { Toaster } from "react-hot-toast";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ToastProvider>
          <NotificationSocketProvider>
            <Navbar />
            {children}
            <Footer />
          </NotificationSocketProvider>
        </ToastProvider>
        <Toaster position="top-right" />
      </body>
    </html>
  );
}
