export enum NotificationType {
    NEW_BOOKING = "NEW_BOOKING",
    BOOKING_CONFIRMED = "BOOKING_CONFIRMED",
    BOOKING_REJECTED = "BOOKING_REJECTED",
    BOOKING_UPDATED = "BOOKING_UPDATED",
    BOOKING_CANCELED_BY_USER = "BOOKING_CANCELED_BY_USER",
  }
  